### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by jaydenwindle** [jaydenwindle/graphene-subscriptions#10]
Now that `graphene-subscriptions` has been out in the wild for a little while, I've noticed a number of common stumbling blocks and areas for improvement. Many thanks to everyone who has raised these issues!

I'd like to address a number of them in the next version of `graphene-subscriptions`. Because some of them will require breaking API changes (most notably #6), the next version of `graphene-subscriptions` will be v2.

I'd like to ship the following features in v2:

- [ ] Allow users to configure Channel Layer groups (#6)
- [ ] Remove Django Signals dependency (#8)
- [ ] Add GraphiQL compatibility (#9)

Please let me know if there are any other issues you would like to see addressed in v2, or if you'd like to work on any of these :)

**Comment by hyusetiawan** [comment]
with graphene v3 release is coming in real soon, is there a beta version of graphene-subscriptions that I can try against the v3 graphene? I volunteer to be a guinea pig :)
